# SwiftLint Configuration for OSX Cleaner
# https://github.com/realm/SwiftLint

# Directories to exclude from linting
excluded:
  - .build
  - .swiftpm
  - Package.swift
  - rust-core

# Rules configuration
disabled_rules:
  - todo  # Allow TODO comments during development

opt_in_rules:
  - empty_count
  - empty_string
  - fatal_error_message
  - first_where
  - force_unwrapping
  - implicitly_unwrapped_optional
  - last_where
  - legacy_random
  - modifier_order
  - overridden_super_call
  - private_action
  - private_outlet
  - prohibited_super_call
  - redundant_nil_coalescing
  - sorted_first_last
  - toggle_bool
  - unavailable_function
  - unowned_variable_capture
  - unused_declaration
  - vertical_parameter_alignment_on_call
  - yoda_condition
  # Security-focused rules
  - explicit_init
  - file_header
  - force_try
  - legacy_hashing
  - nslocalizedstring_key
  - nslocalizedstring_require_bundle
  - private_over_fileprivate
  - strict_fileprivate
  - unneeded_parentheses_in_closure_argument
  - weak_delegate
  - xct_specific_matcher

# Rule configurations
line_length:
  warning: 120
  error: 200
  ignores_comments: true
  ignores_urls: true
  ignores_function_declarations: false
  ignores_interpolated_strings: true

file_length:
  warning: 500
  error: 800
  ignore_comment_only_lines: true

type_body_length:
  warning: 300
  error: 600

function_body_length:
  warning: 50
  error: 100

cyclomatic_complexity:
  warning: 10
  error: 20

large_tuple:
  warning: 3
  error: 4

nesting:
  type_level: 2
  function_level: 3

identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 60
    error: 80
  excluded:
    - id
    - n
    - x
    - y
    - z
    - i
    - j
    - k
    - w
    - c
    - e
    - L    # Localization function
    - mb
    - gb
    - tb
    - ok

trailing_whitespace:
  ignores_empty_lines: true

vertical_whitespace:
  max_empty_lines: 2

# Custom security rules
custom_rules:
  # Detect hardcoded secrets or sensitive data
  hardcoded_secrets:
    name: "Hardcoded Secrets"
    regex: '(?i)(password|secret|token|api[_-]?key|apikey|private[_-]?key)\s*=\s*"[^"]{8,}"'
    message: "Avoid hardcoding secrets, passwords, or API keys in source code"
    severity: error
    match_kinds: string

  # Detect unsafe shell command execution
  shell_injection:
    name: "Potential Shell Injection"
    regex: 'Process\(\)\.run\(|system\(|popen\('
    message: "Potential shell injection vulnerability - validate inputs carefully"
    severity: warning

  # Detect unsafe force casting
  unsafe_force_cast:
    name: "Unsafe Force Cast in Critical Code"
    regex: 'as!\s*\w+'
    message: "Force casting can cause runtime crashes - use optional binding instead"
    severity: warning

  # Detect direct file path construction without validation
  unsafe_path_construction:
    name: "Unsafe Path Construction"
    regex: '"\\/[^"]*"\s*\+|String\(format:\s*"\/[^"]*"'
    message: "Validate and sanitize file paths to prevent directory traversal"
    severity: warning

# Reporter type (xcode, json, csv, checkstyle, junit, html, emoji, sonarqube, markdown, github-actions-logging)
reporter: "xcode"
