# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2021-2025, 🍀☀🌕🌥 🌊

name: OSXCleaner
options:
  bundleIdPrefix: com.kcenon
  deploymentTarget:
    macOS: "14.0"
  developmentLanguage: en
  xcodeVersion: "15.0"
  generateEmptyDirectories: true
  groupSortPosition: top
  createIntermediateGroups: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    MACOSX_DEPLOYMENT_TARGET: "14.0"
    CODE_SIGN_STYLE: Automatic
    DEVELOPMENT_TEAM: ${DEVELOPMENT_TEAM}
    ENABLE_HARDENED_RUNTIME: YES
    OTHER_LDFLAGS:
      - "-L$(PROJECT_DIR)/rust-core/target/release"
      - "-losxcore"
    LIBRARY_SEARCH_PATHS:
      - "$(PROJECT_DIR)/rust-core/target/release"
    SWIFT_INCLUDE_PATHS:
      - "$(PROJECT_DIR)/include"
      - "$(PROJECT_DIR)/Sources/COSXCore"
    HEADER_SEARCH_PATHS:
      - "$(PROJECT_DIR)/include"
    CLANG_ENABLE_MODULES: YES

packages:
  ArgumentParser:
    url: https://github.com/apple/swift-argument-parser.git
    from: "1.3.0"
  Logging:
    url: https://github.com/apple/swift-log.git
    from: "1.5.0"
  Yams:
    url: https://github.com/jpsim/Yams.git
    from: "5.0.0"

targets:
  OSXCleanerGUI:
    type: application
    platform: macOS
    sources:
      - path: Sources/OSXCleanerGUI
        excludes:
          - "**/.DS_Store"
    resources:
      - path: Sources/OSXCleanerGUI/Resources
        buildPhase: resources
    dependencies:
      - target: OSXCleanerKit
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.kcenon.osxcleaner
        PRODUCT_NAME: "OSX Cleaner"
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        INFOPLIST_FILE: Supporting/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        COMBINE_HIDPI_IMAGES: YES
        ENABLE_APP_SANDBOX: YES
        CODE_SIGN_ENTITLEMENTS: Supporting/OSXCleanerGUI.entitlements
        LD_RUNPATH_SEARCH_PATHS:
          - "@executable_path/../Frameworks"
      configs:
        Debug:
          SWIFT_OPTIMIZATION_LEVEL: "-Onone"
          SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG
        Release:
          SWIFT_OPTIMIZATION_LEVEL: "-O"
          SWIFT_COMPILATION_MODE: wholemodule
    info:
      path: Supporting/Info.plist
      properties:
        CFBundleName: "OSX Cleaner"
        CFBundleDisplayName: "OSX Cleaner"
        CFBundleIdentifier: com.kcenon.osxcleaner
        CFBundleVersion: "1"
        CFBundleShortVersionString: "1.0.0"
        CFBundlePackageType: APPL
        CFBundleExecutable: "$(EXECUTABLE_NAME)"
        CFBundleIconFile: AppIcon
        LSMinimumSystemVersion: "$(MACOSX_DEPLOYMENT_TARGET)"
        LSApplicationCategoryType: public.app-category.utilities
        NSPrincipalClass: NSApplication
        NSHighResolutionCapable: true
        NSHumanReadableCopyright: "Copyright © 2021-2025 kcenon. All rights reserved."
        NSSupportsAutomaticTermination: true
        NSSupportsSuddenTermination: false
    entitlements:
      path: Supporting/OSXCleanerGUI.entitlements
      properties:
        com.apple.security.app-sandbox: true
        com.apple.security.files.user-selected.read-write: true
        com.apple.security.files.downloads.read-write: true
        com.apple.security.network.client: true
        com.apple.security.network.server: true
        com.apple.security.files.bookmarks.app-scope: true

  osxcleaner:
    type: tool
    platform: macOS
    sources:
      - path: Sources/osxcleaner
        excludes:
          - "**/.DS_Store"
    dependencies:
      - target: OSXCleanerKit
      - package: ArgumentParser
    settings:
      base:
        PRODUCT_NAME: osxcleaner
        PRODUCT_BUNDLE_IDENTIFIER: com.kcenon.osxcleaner.cli
        ENABLE_HARDENED_RUNTIME: YES
        CODE_SIGN_ENTITLEMENTS: Supporting/osxcleaner.entitlements
      configs:
        Debug:
          SWIFT_OPTIMIZATION_LEVEL: "-Onone"
          SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG
        Release:
          SWIFT_OPTIMIZATION_LEVEL: "-O"
          SWIFT_COMPILATION_MODE: wholemodule
    entitlements:
      path: Supporting/osxcleaner.entitlements
      properties:
        com.apple.security.app-sandbox: false

  OSXCleanerKit:
    type: library.static
    platform: macOS
    sources:
      - path: Sources/OSXCleanerKit
        excludes:
          - "**/.DS_Store"
    dependencies:
      - package: Logging
      - package: Yams
    settings:
      base:
        PRODUCT_NAME: OSXCleanerKit
        SKIP_INSTALL: YES
      configs:
        Debug:
          SWIFT_OPTIMIZATION_LEVEL: "-Onone"
          SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG
        Release:
          SWIFT_OPTIMIZATION_LEVEL: "-O"
          SWIFT_COMPILATION_MODE: wholemodule

  OSXCleanerKitTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - path: Tests/OSXCleanerKitTests
        excludes:
          - "**/.DS_Store"
    dependencies:
      - target: OSXCleanerKit
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.kcenon.osxcleanerkit.tests
        TEST_HOST: ""
        BUNDLE_LOADER: ""

schemes:
  OSXCleanerGUI:
    build:
      targets:
        OSXCleanerGUI: all
        OSXCleanerKit: all
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - OSXCleanerKitTests
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release

  osxcleaner:
    build:
      targets:
        osxcleaner: all
        OSXCleanerKit: all
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - OSXCleanerKitTests
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release

  OSXCleanerKit:
    build:
      targets:
        OSXCleanerKit: all
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - OSXCleanerKitTests
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
